# 스프링에서 어플리케이션 컨텍스트, 디스패쳐서블렛 설정해주는 것들 웬만하면 여기서 설정해주는데
# 웬만한건 디폴트로 설정이 되어 있다.(mvc:annotation 등등)
spring:
#  mvc:
#    static-path-pattern: /content/**
#  static 폴더로 가는 주소값 설정, 없으면 그냥 static 아래 폴더명으로 주소값 연결
#  그럼에도 불구, 컨트롤러가 더 빨라. 컨트롤러에 동명의 핸들러가 있으면 그쪽으로 연결됨.
  thymeleaf: # 뷰리졸버 중 하나 # 참고: cache 빼고는 다 디폴트라 안써도 됨
    check-template-location: true # 템플릿 로케이션을 확인하라..?
    prefix: classpath:templates/
    suffix: .html
    mode: HTML
    cache: false
  datasource: # 히카리는 기본 세팅으로 되어있기 때문에 이렇게만 해줘도 알아서 히카리로다가 거시기 해준다.
    url: jdbc:mysql://localhost:3308/facebook_clone
    username: root
    password: wncks335
    driver-class-name: org.mariadb.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 30MB
      location: C:\SpringRes\facebookClone
  mail:
    host: smtp.gmail.com
    port: 587
    username: sleepydog931025
    password: zdsgdvtztaeigtbf
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 757245212301-7do5b71ok1aicnvtkirgthlgrdfiln9q.apps.googleusercontent.com
            client-secret: 5-zrTd_LBDVnj88z8eyGOTlf
            redirectUri: "{baseUrl}/login/oauth2/code/{registrationId}"
#           uri/login/oauth2/code/ 가 기본구조. 국외 api 는 대부분 이 구조를 따른다.(생략시 디폴트) 국내는 사이트마다 다르기 때문에
#           따로 다 설정 해줘야 한다.
            scope:
              - profile
              - email
          facebook:
            client-id: 251577713084836
            client-secret: 820efa1704d0a438b42dee1cfad56394
            redirectUri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - email
              - public_profile
          kakao:
            authorization-grant-type: authorization_code
            client-id: 89dcfd3c7b09505ca0418f23242ca3aa
            client-secret: sJewH7IumICiFyVmJkYRycNSN4nTxFEV
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - profile_nickname
              - profile_image
            client-authentication-method: POST
            client-name: Kakao
          naver:
            authorization-grant-type: authorization_code
            client-id: GCpbP4RQN_YazH7hxyvo
            client-secret: t0ToKSqMUF
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: name,email,profile_image,mobile,birthyear,age,gender
            client-name: Naver

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: properties
            # JSON 형태에서 "properties"라는 key값에 해당하는 value에 회원 정보가 담겨져있다.
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
            # JSON 형태에서 "response"라는 key값에 해당하는 value에 회원 정보가 담겨져있다.

  devtools:
    livereload:
      enabled: true

mybatis: # mybatis 도 두줄만 ㅎㅎ
  mapper-locations: mybatis-mapper/**/*.xml # resources 폴더 아래에 mybatis-mapper 폴더 안에 폴더수 상관없이 xml파일은 전부
  type-aliases-package: com.koreait.facebook_clone # parameter type 또는 Result Type 에 클래스명만 적으면 이 경로 아래에서 그 클래스(게터세터 있는)를 찾아준다.

# 톰캣 포트 변경
# 포트란?? 내컴퓨터가 아파트라면 포트는 하나의 호실.. 돌아가고 있는 어플리케이션의 주소
server:
  port: 8090 # 생략하면 8080 기본. 8080을 쓰는 어플이 많아 충돌을 염려하여 바꿔준 것

# mail sender 설정